### ISSUE TITLE
Set up CI workflow

### ISSUE THREAD

**Issue by hawschiat** [getbreathelife/onespan-sign-node#6]
### Todos
- [ ] Set up `jest` testing workflow
- [ ] Set up Github workflow to run CI tests
- [ ] Add some basic unit tests to ensure that it works
